/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouterobs (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_espace_agent_de_bureau_de_vote (void);
GtkWidget* create_supprimerobs (void);
GtkWidget* create_statistiques (void);
